### ISSUE TITLE
test.bootSemNeT error

### ISSUE THREAD

**Issue by Mimack** [AlexChristensen/SemNeT#1]
Hi,

I am using the SemNeT package to calculate semantic networks of two datasets. In each datasets two groups are compared and the two files look the same, apart from the animals the participants said. The package works really great with one of the datasets, but not with the other one. For the one with problems I can estimate the networks, compare them to a random network, but I get an error for the bootstrap analysis. The function test.bootSemNeT leads to the error: "Warning: Error in contrasts<-: contrasts can be applied only to factors with 2 or more levels" However, the bootstrap graphs are plotted and they show two groups. This error also only appears if I use the TMFG method with Pearson's correlation. Is there anything in a data set that can lead to such a mistake? 

Best wishes,
Michaela

**Comment by Mimack** [comment]
Hi,

I tried now to do the boostrap analysis with only 10 iterations and 50% of the nodes and that worked. However, when I increase the iterations to 1000 or add the 60% analysis I get the same error as before. The case based analysis works fine. I also tried running the analysis on a different machine, but that did unfortunately not make a difference. Do you think it might be one specific node that is causing this error?

Best wishes,
Michaela

**Comment by AlexChristensen** [comment]
Hi @Mimack,

It's possible that this could be due to a specific node; however, I can't be sure.

Would it be possible for you to email me your data? You can change the node names and remove any IDs. It's more just the data causing the issue that I'll need to see where the bug is occurring.

If so, please send to alexpaulchristensen@gmail.com

Thank you,
Alex

**Comment by AlexChristensen** [comment]
See #3
