### ISSUE TITLE
Error in compare.nets function

### ISSUE THREAD

**Issue by alc5907** [AlexChristensen/SemNeT#5]
**Copy and paste of error from your R console**
```
Error in compare.nets(Young.net, Old.net, title = list("Younger Adults",  : 
  could not find function "compare.nets"
```

**To Reproduce:**
- Function error occurred in: [SemNet]

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNeT Data: [your GitHub username]** *using this template* 

**R and SemNeT versions:**
- R: ["R version 4.0.3 (2020-10-10)"]
- SemNeT: [‘1.4.1’]

**Operating System:**
 - OS: [Windows]
 - Version [10 x64 build 18363]

**Additional context and comments**
- [# Visually compare networks
compare.nets(Young.net, Old.net,
             title = list("Younger Adults", "Older Adults"),
             config = "spring", weighted = TRUE)]

- [worked before but doesn't now]

**Comment by AlexChristensen** [comment]
Hi @alc5907,

This function has changed to `compare_nets`
