### ISSUE TITLE
SemNeTShiny won't install

### ISSUE THREAD

**Issue by mtd143** [AlexChristensen/SemNeT#6]
**Copy and paste of error from your R console**
```
install.packages('SemNeTShiny')
Installing package into ‘/Users/mtd143/Library/R/4.0/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘SemNeTShiny’ is not available for this version of R
```

**To Reproduce:**
- Function error occurred in: [R and RStudio after installing SemNeT 1.3.0 and shiny 1.6.0]

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNeT Data: [mtd143]** *using this template* 

**R and SemNeT versions:**
- R: [4.0.3]
- SemNeT: [e.g., 1.3.0]

**Operating System:**
 - OS: [Mac]
 - Version [Mojave 10.14.6 (18G8022)]

**Additional context and comments**
- [I tried installing in both R and R studio, but get the same error]

**Comment by AlexChristensen** [comment]
`SemNeTShiny()` is a function in the *SemNeT* package
