### ISSUE TITLE
Upload Preprocessed (Binary) Response Matrix

### ISSUE THREAD

**Issue by ezequielfk** [AlexChristensen/SemNeT#7]
**Copy and paste of error from your R console**
Error in stat.cooccur(data, window = window, alpha = alpha):
CN(): Only a response matrix or ordered numeric matrix can be used as input for 'data'
Copy and paste error code here
net.low <- CN(low)

**To Reproduce:**
- Function error occurred in: CN

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNeT Data: ezequielfk** *using this template* 

**R and SemNeT versions:**
- R:  4.1.0
- SemNeT: 1.4.3

**Operating System:**
 - OS: Windows
 - Version: 11

**Additional context and comments**
- I tried running the shiny app SemNeTShiny(). Only in the case of using the steps in the manuscript with the "open.animals" database have I been able to estimate the corresponding networks. However, I have problems when I want to do the analysis with a different database, or when I want to apply the steps directly in R instead of the shiny app.  
In the latter case, I follow the steps in supplementary material 6 (SI6), and I get the following error when running the function net.low <- CN(low):
> net.low <- CN(low)
Error in stat.cooccur(data, window = window, alpha = alpha):
CN(): Only a response matrix or ordered numeric matrix can be used as input for 'data'

A similar problem occurs when I want to incorporate another binary database. In the case of the shiny app, the program stops when trying to load a binary data base (for example, a database of mine, or the "high" database derived from the open.animals database). When I want to incorporate or estimate the network of a binary database, the program crashes (or the corresponding function returns such an error).
My main purpose is to apply the network estimation methods you propose, but from a pre-existing binary database. That is my big obstacle, mainly that when I try to load a binary database to the shiny app the program crashes or gives me the error indicated in the previous message (if I directly run the syntax in R).  
Well I await any help on how to implement the methods you propose but directly on a binary database like the ones I sent you attached (i.e. without the need to select from clean$response in the shiny app).
Thanks!
[high_BRM.csv](https://github.com/AlexChristensen/SemNeT/files/7786167/high_BRM.csv)
[low_BRM.csv](https://github.com/AlexChristensen/SemNeT/files/7786168/low_BRM.csv)
[prueba.csv](https://github.com/AlexChristensen/SemNeT/files/7786169/prueba.csv)

**Comment by AlexChristensen** [comment]
`CN()` does not work with a binary response matrix.

> The community network (CN) method estimates a semantic network using a co-occurrence matrix where two responses (e.g., cat and dog) have occurred within some window or distance from each response for each participant (Goñi et al., 2011) . . . These co-occurrence counts are then used to infer whether [responses] are likely to occur by random chance using confidence intervals from a binomial distribution. 

Because the CN method uses co-occurrence of responses within a certain window, the order of responses must be preserved. A binary response matrix does not preserve this order (but see output `order` in  [`resp2bin`](https://github.com/AlexChristensen/SemNeT/blob/master/R/utils-SemNeT.R))
