### ISSUE TITLE
Error about [: subscript out of bounds

### ISSUE THREAD

**Issue by Ginawsy** [AlexChristensen/SemNeT#8]
**Warning: Error in [: subscript out of bounds**
```
SemNeTShiny()
```

**To Reproduce:**
- Function error occurred in: [e.g., when I would like to estimate network of the method after attaching the textcleaner object variable]

*Optional (but extremely helpful): Attach data to issue or send data to alexpaulchristensen@gmail.com with the subject line* **SemNeT Data: [your GitHub username]** *using this template* 

**R and SemNeT versions:**
- R:4.1.3
- SemNeT: [e.g., 1.4.3]

```


**Operating System:**
 - OS:  [Mac]
 - Version [10.15.7, 13-inch, 2018]

--->

**Additional context and
 comments**
[I put the text cleaner object variable into shiny, and then I try to estimate the network using 4 methods, but neither of them works]
[Attchment includes the data after cleaning
[cleandata.csv](https://github.com/AlexChristensen/SemNeT/files/8457872/cleandata.csv)
]

**Comment by AlexChristensen** [comment]
`group` variable did not match number of cases in data

+ removed row names from examples in Shiny app in 9d74a42769aab9e8f0dfa15f37c87c46c680f340
