### ISSUE TITLE
Phonological Fluency Task

### ISSUE THREAD

**Issue by alc5907** [AlexChristensen/SemNeT#9]
Hi Alex, 
In your SemNA Tutorial paper with Yoed Kenett, you mention that you can use the general dictionary for phonological verbal fluency tasks. My question is, what do you use to create the edges for the phonological network? Siew (2013) and Vitevitch (2002,2008) used phonological similarity between words to determine edges. I did not see specifically what you would use to calculate the edges/edge wights from the SemNet package, but please let me know if I missed something. 
Thank you,
Abby

**Comment by AlexChristensen** [comment]
In {SemNeT}, the associations are estimated based on the co-occurrence of responses generated across participants.

In the Siew and Vitevitch papers, use different phonological similarity measures that are not available in {SemNeT}
